### ISSUE TITLE
can check item for config ?

### ISSUE THREAD

**Issue by haitham1337** [KrisKingo/kk-doorlock#1]

**Comment by KrisKingo** [comment]
Hmm i can make it, but i think it will have a massive performance decrease..

**Comment by haitham1337** [comment]
I mean for example  keyfob 
Checks if the player owns the item or not
It gives him access

**Comment by KrisKingo** [comment]
Yeah i know, but the thing is, if its gonna check every slot of you inventory it will have a massive performance impact, and i don't think it will be very good. But i can maybe see if i can but something together.
